
import os
import json
import subprocess
from dotenv import load_dotenv

# Load API key from .env
load_dotenv()

api_key = os.getenv("BOB_API_KEY")

if not api_key:
    raise RuntimeError("BOB_API_KEY not found in .env")

# Load the anomaly context generated by our ML pipeline
with open("data/sample_ai_context.txt", "r", encoding="utf-8") as f:
    context = f.read()

prompt = f"""
You are the AI explanation layer of GreenLoad AI.

Analyze the following energy anomaly context and produce a
careful, evidence-based explanation.

Return ONLY valid JSON with exactly these keys:
summary
evidence
shap_explanation
possible_explanations
recommendations
limitations

IMPORTANT RULES:

1. Use only information explicitly present in the provided context.

2. Clearly distinguish:
   - OBSERVED: directly supported by the numerical data.
   - POSSIBLE: reasonable interpretations that are NOT confirmed causes.

3. Never claim that a specific appliance caused the anomaly unless the
   data directly identifies that appliance. Sub-metering identifies
   circuit groups, not individual appliances.

4. Do not assume anything about:
   - whether people were awake or asleep
   - occupancy
   - user behavior
   - household routines
   - weather
   - electricity tariffs
   - appliance schedules

5. Do not use phrases such as "should be near-idle", "occupants are
   likely asleep", or similar assumptions unless that exact conclusion
   is directly supported by the supplied numerical evidence.

6. Do not invent appliance examples as if they were detected causes.
   If giving an example, explicitly label it as a hypothetical example.

7. For recommendations, only recommend actions that logically follow
   from the measured evidence. Recommendations should focus on
   investigating unusual consumption, monitoring high-load circuits,
   and reducing consumption where the data supports it.

8. SHAP values explain contributions to the Isolation Forest RAW TREE
   OUTPUT. Do NOT say that a negative SHAP value directly means
   "more anomalous". Do not confuse SHAP values with the
   decision_function anomaly score.

9. Do not claim that voltage changes are caused by the high load unless
   the data proves causality. Describe the voltage difference as an
   observation only.

10. Do not call the anomaly "statistically significant" unless a
    statistical significance test is actually provided. Use
    "classified as an anomaly" instead.

11. Keep explanations concise enough for a dashboard while retaining
    the important numerical evidence.

CONTEXT:
{context}
"""

# Pass the API key to Bob Shell through the environment
env = os.environ.copy()
env["BOBSHELL_API_KEY"] = api_key

# Run Bob Shell in headless mode.
# The prompt is passed through stdin because it is a large multi-line prompt.
result = subprocess.run(
    [
        r"C:\Users\vidit\AppData\Roaming\npm\bob.cmd",
        "run",
        "-f",
        "json"
    ],
    input=prompt,
    capture_output=True,
    text=True,
    encoding="utf-8",
    env=env
)

if result.returncode != 0:
    print("Bob Shell failed.")
    print(result.stderr)
    raise SystemExit(result.returncode)

# Parse Bob Shell's outer JSON response
try:
    bob_result = json.loads(result.stdout)
except json.JSONDecodeError as e:
    print("Could not parse Bob Shell output.")
    print(result.stdout)
    raise SystemExit(1) from e

# Get Bob's actual AI response
last_message = bob_result.get("last_message")

if not last_message:
    print("Bob response did not contain 'last_message'.")
    print(result.stdout)
    raise SystemExit(1)

# Remove Markdown code fences if Bob returned ```json ... ```
clean_message = last_message.strip()

if clean_message.startswith("```json"):
    clean_message = clean_message[len("```json"):].strip()

if clean_message.endswith("```"):
    clean_message = clean_message[:-3].strip()

# Parse Bob's actual JSON response
try:
    explanation = json.loads(clean_message)
except json.JSONDecodeError as e:
    print("Bob returned a response that is not valid JSON.")
    print(clean_message)
    raise SystemExit(1) from e

# Save the clean explanation for the dashboard/backend
output_file = "data/bob_explanation.json"

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(explanation, f, indent=2, ensure_ascii=False)

print("Bob explanation generated successfully!")
print(f"Saved to: {output_file}")

print("\nTop-level keys:")
for key in explanation:
    print(f"- {key}")

